version: '3'
services:

  notification_center:
    container_name: 321cqu-notification-center
    build: .
    expose:
      - "53210"
    restart: always
    volumes:
      - /www/services/notification_center/config:/src/utils/config
    networks:
      - persist

networks:
  persist:
    external:
      name: 321cqu

