# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apns.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\napns.proto\".\n\x12SetUserApnsRequest\x12\x0b\n\x03sid\x18\x01 \x01(\t\x12\x0b\n\x03\x61pn\x18\x02 \x01(\t\"2\n\x13SetUserApnsResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t2@\n\x04\x41pns\x12\x38\n\x0bSetUserApns\x12\x13.SetUserApnsRequest\x1a\x14.SetUserApnsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apns_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETUSERAPNSREQUEST._serialized_start=14
  _SETUSERAPNSREQUEST._serialized_end=60
  _SETUSERAPNSRESPONSE._serialized_start=62
  _SETUSERAPNSRESPONSE._serialized_end=112
  _APNS._serialized_start=114
  _APNS._serialized_end=178
# @@protoc_insertion_point(module_scope)
