# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apns.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\napns.proto\x1a\x19google/protobuf/any.proto\".\n\x12SetUserApnsRequest\x12\x0b\n\x03sid\x18\x01 \x01(\t\x12\x0b\n\x03\x61pn\x18\x02 \x01(\t\"`\n\x0f\x44\x65\x66\x61ultResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\'\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x88\x01\x01\x42\x07\n\x05_data\"\xb4\x02\n\x17SendNotificationRequest\x12\x0b\n\x03sid\x18\x01 \x01(\t\x12@\n\x0cnotification\x18\x02 \x01(\x0b\x32*.SendNotificationRequest.AppleNotification\x1a\xc9\x01\n\x11\x41ppleNotification\x12\x44\n\x05\x61lert\x18\x01 \x01(\x0b\x32\x35.SendNotificationRequest.AppleNotification.AppleAlert\x12\r\n\x05\x62\x61\x64ge\x18\x02 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x1aM\n\nAppleAlert\x12\r\n\x05title\x18\x01 \x01(\t\x12\x15\n\x08subtitle\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x0c\n\x04\x62ody\x18\x03 \x01(\tB\x0b\n\t_subtitle2\x82\x01\n\x04\x41pns\x12\x34\n\x0bSetUserApns\x12\x13.SetUserApnsRequest\x1a\x10.DefaultResponse\x12\x44\n\x16SendNotificationToUser\x12\x18.SendNotificationRequest\x1a\x10.DefaultResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apns_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETUSERAPNSREQUEST._serialized_start=41
  _SETUSERAPNSREQUEST._serialized_end=87
  _DEFAULTRESPONSE._serialized_start=89
  _DEFAULTRESPONSE._serialized_end=185
  _SENDNOTIFICATIONREQUEST._serialized_start=188
  _SENDNOTIFICATIONREQUEST._serialized_end=496
  _SENDNOTIFICATIONREQUEST_APPLENOTIFICATION._serialized_start=295
  _SENDNOTIFICATIONREQUEST_APPLENOTIFICATION._serialized_end=496
  _SENDNOTIFICATIONREQUEST_APPLENOTIFICATION_APPLEALERT._serialized_start=419
  _SENDNOTIFICATIONREQUEST_APPLENOTIFICATION_APPLEALERT._serialized_end=496
  _APNS._serialized_start=499
  _APNS._serialized_end=629
# @@protoc_insertion_point(module_scope)
